[2025-05-15T15:07:30.984+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1598472442.summarize_daily_posts scheduled__2025-05-15T14:30:00+00:00 [queued]>
[2025-05-15T15:07:30.989+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1598472442.summarize_daily_posts scheduled__2025-05-15T14:30:00+00:00 [queued]>
[2025-05-15T15:07:30.990+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-15T15:07:31.002+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): summarize_daily_posts> on 2025-05-15 14:30:00+00:00
[2025-05-15T15:07:31.014+0000] {standard_task_runner.py:60} INFO - Started process 280 to run task
[2025-05-15T15:07:31.018+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1598472442', 'summarize_daily_posts', 'scheduled__2025-05-15T14:30:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmpm676pn7l']
[2025-05-15T15:07:31.021+0000] {standard_task_runner.py:88} INFO - Job 143: Subtask summarize_daily_posts
[2025-05-15T15:07:31.045+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T15:07:31.088+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1598472442.summarize_daily_posts scheduled__2025-05-15T14:30:00+00:00 [running]> on host 9c6602089b4d
[2025-05-15T15:07:31.163+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1598472442' AIRFLOW_CTX_TASK_ID='summarize_daily_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-15T14:30:00+00:00'
[2025-05-15T15:07:31.241+0000] {docker.py:359} INFO - Starting docker container from image telegram_summarizer_task:latest
[2025-05-15T15:07:31.937+0000] {docker.py:429} INFO - [2025-05-15 15:07:31] [INFO] [Summarizer] - --- Запуск скрипта суммризации (Airflow Task) ---
[2025-05-15 15:07:31] [INFO] [Summarizer] - Попытка чтения XCom из /airflow/xcom/return.json
[2025-05-15 15:07:31] [ERROR] [Summarizer] - Ошибка: Файл XCom '/airflow/xcom/return.json' не найден.
[2025-05-15 15:07:31] [WARNING] [Summarizer] - Скрипт завершается с кодом: 1
[2025-05-15T15:07:31.938+0000] {docker.py:429} INFO - [2025-05-15 15:07:31] [INFO] [Summarizer] - --- Скрипт суммризации завершен с кодом выхода: 1 ---
[2025-05-15T15:07:32.316+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-05-15T15:07:32.320+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=telegram_summary_channel_1598472442, task_id=summarize_daily_posts, execution_date=20250515T143000, start_date=20250515T150730, end_date=20250515T150732
[2025-05-15T15:07:32.348+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 143 for task summarize_daily_posts (Docker container failed: {'StatusCode': 1}; 280)
[2025-05-15T15:07:32.393+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T15:07:32.419+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
